### ISSUE TITLE
macOS: first button in sidebar hidden in full screen

### ISSUE THREAD

**Issue by majouji** [jordansinger/SwiftUI-Kit#10]
This might be a bug with SwiftUI itself (not the first time I’m seeing this with `Sidebar()`, but capturing here in case someone knows a fix.

When entering in full screen mode, the first button in the sidebar view is hidden by the toolbar.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/23482161/87231240-66242b80-c383-11ea-9444-3546eff5a6e9.gif)

**Comment by Nef10** [comment]
This seems to be fixed in the final Big Sur build
