### ISSUE TITLE
Set view previews to .sizeThatFits?

### ISSUE THREAD

**Issue by majouji** [jordansinger/SwiftUI-Kit#2]
Love this repo – so helpful! Something Apple should provide themselves.

Previews for extracted views (like the files in the Groupings folder) are shown in an iPhone frame by default (since the scheme is set to iPhone SE) – I wonder if it would make sense to change the preview layout to `.previewLayout(.sizeThatFits)` for these.

Having the iPhone chrome can imply/suggest that it’s a "screen" rather than an isolated piece of UI (I can see this being confusing for someone starting out who isn’t familiar with breaking up views in multiple files).

I can create a PR for it but wanted to check first!

Updated preview would look like this:
<img width="478" alt="Screen Shot 2020-07-10 at 21 37 25" src="https://user-images.githubusercontent.com/23482161/87213798-9329fd00-c2f5-11ea-8184-f5ae286f1c7e.png">

**Comment by jordansinger** [comment]
This is a wonderful addition! PR appreciated
