### ISSUE TITLE
Can't dismiss ColorPicker Control

### ISSUE THREAD

**Issue by ivanglushko** [jordansinger/SwiftUI-Kit#26]

**Comment by majouji** [comment]
@ivanglushko, mind giving a bit more info here?

Specific steps to reproduce would be helpful to look into fixing it. Thanks!

**Comment by ivanglushko** [comment]
@majouji oh yeah sorry. 
iOS Target.
So basically if you're going to open Color Picker control you can't dismiss a modal vc like you usually do.
I'm using simulator iPhone X iOS 14
<img width="535" alt="Screenshot 2020-07-12 at 20 51 08" src="https://user-images.githubusercontent.com/36343782/87254240-6acf0980-c481-11ea-872d-3d76b13c7c35.png">

**Comment by kernjackson** [comment]
@majouji This is a SwiftUI bug that was fixed in Xcode version 12.0 beta 2 (12A6163b).

**Comment by ivanglushko** [comment]
> @majouji This is a SwiftUI bug that was fixed in Xcode version 12.0 beta 2 (12A6163b).

I'm using beta 1. Bug fixed. Now we can close ah issue
