### ISSUE TITLE
Add Widget examples

### ISSUE THREAD

**Issue by majouji** [jordansinger/SwiftUI-Kit#31]
Would be great to have some code example of SwiftUI for Widget Kit!

**Comment by jordansinger** [comment]
Oh yes that’s awesome. Makes me wonder what other kinds of system things like this are worth supporting?

**Comment by tbraun1551** [comment]
What would we want the Widget to show?

**Comment by aaryankotharii** [comment]
@majouji @jordansinger @tbraun1551  How about a simple widget showing current date and time?

**Comment by tbraun1551** [comment]
In my last pull request I included a Widget that just had a 'title' and the current time. Wasn't really sure what else to put in.

**Comment by Nef10** [comment]
Closing, widgets were added in #40 

However, feel free to continue improve the widgets.
