### ISSUE TITLE
Visual Studio Code support?

### ISSUE THREAD

**Issue by markst** [jordansinger/SwiftUI-Kit#46]
In VSCode using 'iOS Debug' it's possible to build & debug iOS Simulator applications. 
https://marketplace.visualstudio.com/items?itemName=nisargjhaveri.ios-debug

I'm wondering whether there might be interest in using VSCode to hot reload:

![vscode-hotreload](https://user-images.githubusercontent.com/274318/171166804-7390bd33-a76e-4a4d-807c-311cf5a11888.gif)

**Comment by markst** [comment]
There's also: https://marketplace.visualstudio.com/items?itemName=Kenny.lightcodeios

**Comment by markst** [comment]
I have a fork here for those interested: https://github.com/markst/SwiftUI-Kit/tree/feature/vscode

**Comment by markst** [comment]
What I can't seem to get working is the `start_daemon` task to launch `injectiond` on build:
https://github.com/markst/SwiftUI-Kit/blob/feature/vscode/.vscode/tasks.json#L32

**Comment by markst** [comment]
Oops this is only relevant to @johnno1962's fork

**Comment by johnno1962** [comment]
You shouldn't need to run the daemon script any more unless you are injecting on a device.
